name = "hello-containers"
main = "src/index.ts"
compatibility_date = "2025-05-23"
compatibility_flags = ["nodejs_compat"]

[[containers]]
class_name = "MyContainer"
image = "./Dockerfile"
max_instances = 10

[[migrations]]
new_sqlite_classes = ["MyContainer"]
tag = "v1"

[observability]
enabled = true

[[durable_objects.bindings]]
class_name = "MyContainer"
name = "MY_CONTAINER"
